<?php
$logon_source="LocalSYS";
$loc_sys_rcd="/etc/init.d/";
$loc_sys_sudo="yes";
$loc_sys_conf_mac="";
$loc_sys_conf_dhcp="";
$loc_sys_conf_ifaces="";
$loc_sys_conf_samba="";
$loc_sys_shell="/bin/bash";
$loc_sys_distro="Debian/Ubuntu";
$loc_sys_ver="6";
$enable_register="yes";
$locale="pl-PL-utf8";
?>
